# Generated by Django 3.2 on 2022-05-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malawiplace_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookFlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BookRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='RentCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='capacity',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='flight',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='Final_destination',
            field=models.CharField(choices=[('Paris', 'Paris'), ('New York', 'New York'), ('London ', 'London')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='depature_place',
            field=models.CharField(choices=[('lilongwe', 'lilongwe'), ('Blantyre', 'Blantyre'), ('Mzuzu', 'Mzuzu')], max_length=200, null=True),
        ),
    ]
