# Generated by Django 3.2 on 2022-05-07 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malawiplace_app', '0002_auto_20220506_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='rooms',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AddField(
            model_name='room',
            name='num_of_beds',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
