# Generated by Django 3.2 on 2022-05-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malawiplace_app', '0003_auto_20220507_0227'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='destination',
            field=models.CharField(choices=[('lilongwe', 'lilongwe'), ('Blantyre', 'Blantyre'), ('Mzuzu', 'Mzuzu')], max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(choices=[('Executive', 'Executive'), ('Standard', 'Standard'), ('Small', 'Small')], max_length=100, null=True),
        ),
    ]
