# Generated by Django 3.2 on 2022-05-08 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malawiplace_app', '0005_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='bus',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='car',
            name='pick_up_location',
            field=models.CharField(choices=[('lilongwe', 'lilongwe'), ('Blantyre', 'Blantyre'), ('Mzuzu', 'Mzuzu')], max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='cabin_class',
            field=models.CharField(choices=[('First Class', 'First Class'), ('Economy', 'Economy'), ('Standard', 'Standard')], max_length=100, null=True),
        ),
    ]
