# Generated by Django 3.2 on 2022-05-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malawiplace_app', '0006_auto_20220508_1958'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='price',
            field=models.FloatField(default=0, null=True),
        ),
    ]
