# Generated by Django 3.2 on 2022-05-21 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malawiplace_app', '0012_blog_content_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='event_img/')),
                ('event_name', models.CharField(max_length=200, null=True)),
                ('event_description', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('location', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Restrant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('restrant_name', models.CharField(max_length=300, null=True)),
                ('location', models.CharField(max_length=200, null=True)),
                ('logo', models.ImageField(upload_to='restrant_img/')),
            ],
        ),
    ]
