# Generated by Django 3.2 on 2022-05-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malawiplace_app', '0013_event_restrant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_or_country', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
