# Generated by Django 3.2 on 2022-05-31 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malawiplace_app', '0014_placecountry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Place',
        ),
        migrations.DeleteModel(
            name='PlaceCountry',
        ),
    ]
