# Generated by Django 3.2 on 2022-05-31 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malawiplace_app', '0017_auto_20220531_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlaceCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('continent_or_country', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place_name', models.CharField(max_length=200, null=True)),
                ('about_place', models.TextField(null=True)),
                ('extra_content', models.TextField(null=True)),
                ('img', models.ImageField(upload_to='places/')),
                ('place_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='malawiplace_app.placecountry')),
            ],
        ),
    ]
