# Generated by Django 4.0.5 on 2022-06-12 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malawiplace_app', '0018_place_placecountry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRoom',
        ),
        migrations.AddField(
            model_name='hotel',
            name='slug',
            field=models.SlugField(default='hotel', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hotel',
            name='hotel_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
