# Generated by Django 4.0.5 on 2022-06-14 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malawiplace_app', '0020_bookroom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BookRoom',
        ),
    ]
