# Generated by Django 4.0.5 on 2022-06-12 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('malawiplace_app', '0020_bookroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookroom',
            name='additional_reservations',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='bookroom',
            name='number_of_rooms',
            field=models.IntegerField(default=1),
        ),
    ]
