# Generated by Django 4.0.5 on 2022-06-15 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('malawiplace_app', '0021_bookroom_additional_reservations_and_more'),
        ('malawiplace_app', '0022_bookroom'),
    ]

    operations = [
    ]
