# Generated by Django 4.0.5 on 2022-06-15 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malawiplace_app', '0023_merge_20220615_1429'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, null=True)),
                ('buses', models.IntegerField(default=1, null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('bus_logo', models.ImageField(upload_to='bus_company_img')),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_name', models.CharField(max_length=255, null=True)),
                ('depature_point', models.CharField(max_length=255, null=True)),
                ('destination_point', models.CharField(max_length=255, null=True)),
                ('price', models.FloatField(default=0.0)),
                ('depature_time', models.TimeField(null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('max_capacity', models.PositiveIntegerField(default=1)),
                ('bus_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='malawiplace_app.buscompany')),
            ],
            options={
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='BookBus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('passenger_name', models.CharField(max_length=255, null=True)),
                ('number_of_seats', models.IntegerField(default=1)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(default='+265', max_length=255, null=True)),
                ('bus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='malawiplace_app.bus')),
            ],
        ),
    ]
