# Generated by Django 4.0.5 on 2022-06-16 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('malawiplace_app', '0025_alter_bookbus_options_alter_buscompany_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone_number', models.CharField(default='+265', max_length=255, null=True)),
                ('number_of_tickets', models.PositiveIntegerField(default=1)),
                ('name_of_event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='malawiplace_app.event')),
            ],
        ),
    ]
