# Generated by Django 4.0.5 on 2022-06-22 20:54

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('malawiplace_app', '0027_room_is_booked'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='room',
            managers=[
                ('room', django.db.models.manager.Manager()),
            ],
        ),
    ]
